name: Deploy Node.js App with PM2
on:
  push:
    branches:
      - main # Chỉ khi commit lên nhánh main mới chạy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no username@hostname_or_ip_address << 'EOF'
            cd /root/simple-api
            git pull origin main
            npm install
            pm2 reload ecosystem.config.js --env production
          EOF
